services:
  redis:
    image: redis/redis-stack-server:latest
    container_name: redis
    ports:
      - "6379:6379" # 任务通信端口
      - "8001:8001" # Redis Insight 可视化界面
    networks:
      - ai_network

  controller:
    build: ./controller
    container_name: controller
    ports:
      - "9000:9000"
    volumes:
      - ./temp_data:/app/tmp
      - ./data:/app/data
    environment:
      - SHARED_PATH=/app/tmp
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    networks:
      - ai_network

  worker:
    build: ./worker
    container_name: worker
    volumes:
      - ./temp_data:/app/tmp
      - ./data:/app/data
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - AUDIO_HOST=audioservice # 对应下方的服务名
      - AUDIO_PORT=8000 # 容器内原始端口
      - VISUAL_HOST=visualservice # 对应下方的服务名
      - VISUAL_PORT=8000 # 容器内原始端口
    # 在 A100 上，我们开启并发 2，让音频和视觉任务同时进行
    command: celery -A tasks worker --loglevel=info --concurrency=2
    depends_on:
      - redis
      - audioservice
      - service3_visual
    networks:
      - ai_network

  audioservice:
    image: audioservice:latest # 你 load 进来的本地镜像名
    container_name: audioservice
    ports:
      - "9002:8000" # 宿主机用 9002 访问，内部是 8000
    volumes:
      - ./temp_data:/app/tmp
    environment:
      - SHARED_PATH=/app/tmp
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1 # 占用 A100 GPU
              capabilities: [ gpu ]
    networks:
      - ai_network

  # 5. 视觉推理服务 (Service 3)
  service3_visual:
    image: visualservice:latest # 假设你的视觉服务镜像名
    container_name: visualservice
    ports:
      - "9001:8000" # 宿主机用 9001 访问，内部是 8000
    volumes:
      - ./temp_data:/app/tmp
    environment:
      - SHARED_PATH=/app/tmp
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    networks:
      - ai_network

networks:
  ai_network:
    driver: bridge
